// Generated by CoffeeScript 1.6.3
var TodosCollection, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = TodosCollection = (function(_super) {
  __extends(TodosCollection, _super);

  function TodosCollection() {
    _ref = TodosCollection.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodosCollection.prototype.model = require('models/Todo');

  TodosCollection.prototype.initialize = function() {};

  return TodosCollection;

})(Backbone.Collection);

this.localStorage = new Store('todos');

({
  done: function() {
    return this.filter(function(todo) {
      return todo.get('done');
    });
  },
  remaining: function() {
    return this.without.apply(this, this.done());
  },
  nextOrder: function() {
    if (!this.length) {
      return 1;
    }
    return this.last().get('order') + 1;
  },
  comparator: function(todo) {
    return todo.get('order');
  },
  clearCompleted: function() {
    return _.each(this.done(), function(todo) {
      return todo.clear();
    });
  }
});
