// Generated by CoffeeScript 1.6.3
var TodosCollection, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = TodosCollection = (function(_super) {
  __extends(TodosCollection, _super);

  function TodosCollection() {
    _ref = TodosCollection.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodosCollection.prototype.model = require('models/Todo');

  return TodosCollection;

})(Backbone.Collection);
