// Generated by CoffeeScript 1.6.3
var TodoModel, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = TodoModel = (function(_super) {
  __extends(TodoModel, _super);

  function TodoModel() {
    _ref = TodoModel.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodoModel.prototype.defaults = {
    content: 'مافيه شيء',
    done: false,
    list: 'inbox'
  };

  TodoModel.prototype.toggle = function() {
    return this.save({
      done: !this.get('done')
    });
  };

  TodoModel.prototype.clear = function() {
    this.destroy();
    return this.view.remove();
  };

  return TodoModel;

})(Backbone.Model);
