// Generated by CoffeeScript 1.6.3
var HomeViewView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = HomeViewView = (function(_super) {
  __extends(HomeViewView, _super);

  function HomeViewView() {
    _ref = HomeViewView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HomeViewView.prototype.className = 'home_view';

  HomeViewView.prototype.template = './templates/home';

  return HomeViewView;

})(Backbone.View);

({
  el: '#home-view',
  afterRender: function() {
    var $todo, viewName, _i, _len, _ref1, _results;
    $todo = this.$el.find('#app-wrapper');
    _ref1 = ['newTodo', 'todos', 'stats'];
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      viewName = _ref1[_i];
      _results.push($todo.append(application["" + viewName + "View"].render().el));
    }
    return _results;
  }
});
