// Generated by CoffeeScript 1.6.3
var StatsViewView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = StatsViewView = (function(_super) {
  __extends(StatsViewView, _super);

  function StatsViewView() {
    _ref = StatsViewView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  StatsViewView.prototype.className = 'stats_view';

  return StatsViewView;

})(Backbone.View);

({
  template: require('./templates/stats'),
  id: 'stats-view',
  events: {
    'click .todo-clear': 'clearCompleted'
  },
  getRenderData: function() {
    return {
      stats: {
        total: application.todos.length,
        done: application.todos.done().length,
        remaining: application.todos.remaining().length
      }
    };
  },
  clearCompleted: function() {
    return application.todos.clearCompleted();
  }
});
