// Generated by CoffeeScript 1.6.3
var TodoView, TodosViewView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  _this = this;

module.exports = TodosViewView = (function(_super) {
  __extends(TodosViewView, _super);

  function TodosViewView() {
    _ref = TodosViewView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodosViewView.prototype.className = 'todos_view';

  return TodosViewView;

})(Backbone.View);

TodoView = todo_view;

({
  template: require('./templates/todos'),
  id: 'todos-view',
  addOne: function(todo) {
    var view;
    view = new TodoView({
      model: todo
    });
    return _this.$el.find('#todos').append(view.render().el);
  },
  addAll: function() {
    return application.todos.each(_this.addOne);
  },
  initialize: function() {
    application.todos.bind('add', this.addOne);
    application.todos.bind('reset', this.addAll);
    return application.todos.bind('all', this.renderStats);
  },
  renderStats: function() {
    return application.statsView.render();
  }
});
